/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        ink: { DEFAULT: '#111111', soft: '#1A1A1A', muted: '#2D2D2D' },
        gold: { DEFAULT: '#9A7F2E', light: '#B89A4A', dark: '#7D6624', pale: '#C4A84D' },
        sand: '#FAFAFA',
        surface: '#FAFAFA',
        line: '#E0E0E0',
        muted: '#5C5C5C',
        subtle: '#8A8A8A',
        faint: '#A3A3A3',
        dim: '#D4D4D4',
        maroon: { DEFAULT: '#111111', dark: '#000000', light: '#9A7F2E' },
        success: '#2E7D32',
        warning: '#E65100',
      },
      fontFamily: {
        sans: [
          'Plus Jakarta Sans',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'sans-serif',
        ],
        display: [
          'Lemon Milk',
          'Plus Jakarta Sans',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        DEFAULT: '6px',
        md: '6px',
        lg: '6px',
        xl: '6px',
        '2xl': '6px',
        '3xl': '6px',
        full: '9999px',
      },
      boxShadow: {
        none: 'none',
        sm: 'none',
        DEFAULT: 'none',
        md: 'none',
        lg: 'none',
        xl: 'none',
        '2xl': 'none',
        inner: 'none',
        card: '0 1px 3px rgba(17, 17, 17, 0.06)',
      },
    },
  },
  plugins: [],
};
